/**
 * DTV UI Elements Module
 * Contiene todas las referencias al DOM utilizadas en la aplicación.
 */
export const ELEMENTS = window.ELEMENTS = {
    chatBox: document.getElementById('chatBox'),
    chatInput: document.getElementById('chatMentoriaInput'),
    chatInputArea: document.querySelector('.input-area'),
    sendBtn: document.getElementById('sendBtn'),
    micBtn: document.getElementById('micBtn'),
    authOverlay: document.getElementById('authOverlay'),
    authError: document.getElementById('authError'),
    mainHelpBtn: document.getElementById('mainHelpBtn'),
    mainHelpTooltip: document.getElementById('mainHelpTooltip'),
    headerButtons: document.querySelector('.header-buttons'),
    navButtons: {
        inspiracion: document.getElementById('inspiracionBtn'),
        viaje: document.getElementById('viajeBtn'),
        progreso: document.getElementById('progresoBtn'),
        botiquin: document.getElementById('botiquinBtn'),
        logout: document.getElementById('logoutBtn')
    },
    loginFields: document.getElementById('loginFields'),
    forgotPasswordLink: document.getElementById('forgotPasswordLink'),
    resetPasswordContainer: document.getElementById('resetPasswordContainer'),
    updatePasswordBtn: document.getElementById('updatePasswordBtn'),
    upgradeBtn: document.getElementById('upgradeBtn'),
    whatsappReportBtn: document.getElementById('whatsappReportBtn'),
    upgradeModal: document.getElementById('upgradeModal'),
    closeUpgrade: document.querySelector('.close-upgrade'),
    sesionBtn: document.getElementById('sesionBtn'),
    sesionModal: document.getElementById('sesionModal'),
    closeSesion: document.getElementById('closeSesion'),
    sessionQuotaInfo: document.getElementById('sessionQuotaInfo'),
    book30Btn: document.getElementById('book30Btn'),
    book60Btn: document.getElementById('book60Btn'),
    buyExtra30Btn: document.getElementById('buyExtra30Btn'),
    buyExtra60Btn: document.getElementById('buyExtra60Btn'),
    // Payment Modal (In-App)
    paymentModal: document.getElementById('paymentModal'),
    closePayment: document.getElementById('closePayment'),
    paymentForm: document.getElementById('payment-form'),
    paymentElement: document.getElementById('payment-element'),
    submitPayment: document.getElementById('submit-payment'),
    paymentSpinner: document.getElementById('payment-spinner'),
    paymentMessage: document.getElementById('payment-message'),
    buttonText: document.getElementById('button-text'),
    ajustesBtn: document.getElementById('ajustesBtn'),
    settingsModal: document.getElementById('settingsModal'),
    closeSettings: document.querySelector('.close-settings'),
    saveSettingsBtn: document.getElementById('saveSettingsBtn'),
    clearHistoryBtn: document.getElementById('clearHistoryBtn'),
    settingsUserName: document.getElementById('settingsUserName'),
    settingsUserTier: document.getElementById('settingsUserTier'),
    focusSlider: document.getElementById('focusSlider'),
    personalitySlider: document.getElementById('personalitySlider'),
    lengthSlider: document.getElementById('lengthSlider'),
    languageSelect: document.getElementById('languageSelect'),
    weeklyGoalInput: document.getElementById('weeklyGoalInput'),
    upgradeSettingsBtn: document.getElementById('upgradeSettingsBtn'),
    // Legal Modal
    legalModal: document.getElementById('legalModal'),
    checkTerms: document.getElementById('checkTerms'),
    checkMedical: document.getElementById('checkMedical'),
    confirmLegalBtn: document.getElementById('confirmLegalBtn'),
    cancelLegalBtn: document.getElementById('cancelLegalBtn'),
    // Soporte Híbrido
    supportBubble: document.getElementById('supportBubble'),
    supportModal: document.getElementById('supportModal'),
    supportChatBox: document.getElementById('supportChatBox'),
    supportInput: document.getElementById('supportInput'),
    sendSupportBtn: document.getElementById('sendSupportBtn'),
    whatsappSupportLink: document.getElementById('whatsappSupportLink'),
    closeSupport: document.querySelector('.close-support'),
    // Modal de Inspiración
    inspiracionModal: document.getElementById('inspiracionModal'),
    inspiracionFrase: document.querySelector('.inspiracion-frase'),
    inspiracionAutor: document.querySelector('.inspiracion-autor'),
    closeInspiracion: document.getElementById('closeInspiracion'),
    // Botiquín Modal
    botiquinModal: document.getElementById('botiquinModal'),
    botiquinContent: document.getElementById('botiquinContent'),
    closeBotiquin: document.querySelector('.close-botiquin'),
    // Preferencias Modal
    openPreferencesBtn: document.getElementById('openPreferencesBtn'),
    preferencesModal: document.getElementById('preferencesModal'),
    closePreferences: document.querySelector('.close-preferences'),
    marketingToggle: document.getElementById('marketingToggle'),
    lifecycleToggle: document.getElementById('lifecycleToggle'),
    savePreferencesBtn: document.getElementById('savePreferencesBtn'),
    prefStatusMessage: document.getElementById('prefStatusMessage'),
    deleteAccountBtn: document.getElementById('deleteAccountBtn'),
    // Alert Custom
    customAlert: document.getElementById('customAlert'),
    alertMessage: document.getElementById('alertMessage'),
    alertConfirmBtn: document.getElementById('alertConfirmBtn'),
    promoTermsBox: document.getElementById('promoTermsBox'),
    // Top Bar Music Player
    musicToggleBtn: document.getElementById('musicToggleBtn'),
    musicMenu: document.getElementById('musicMenu'),
    musicListItems: document.getElementById('musicListItems'),
    stopMusicBtn: document.getElementById('stopMusicBtn'),
    // Quick Actions
    quickUploadBtn: document.getElementById('quickUploadBtn'),
    quickPhoneticsBtn: document.getElementById('quickPhoneticsBtn'),
    phoneticsMenu: document.getElementById('phoneticsMenu')
};
